In [3]:
from FLamby.flamby.datasets.fed_tcga_brca import FedTcgaBrca 
from torch.utils.data import DataLoader as dl

In [4]:
center0 = FedTcgaBrca(center=0, train=True)
c0 = iter(dl(center0, batch_size=4, shuffle=True, num_workers=0))

In [5]:
point, target = next(c0)
print(point)
print(target)
print(point.shape)
print(target.shape)

tensor([[52.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,
          0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [46.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
          1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.],
        [41.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
          1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,
          0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.],
        [60.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,
          0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])
tensor([[0.0000e+00, 1.8200e+03],
        [0.0000e+00, 6.2200e+02],
        [0.0000e+00, 2.4030e+03],
     

In [13]:
from FLamby.flamby.datasets.fed_heart_disease import FedHeartDisease


In [42]:
center1 = FedHeartDisease(center=1, train=True)
c1 = iter(dl(center1, batch_size=16, shuffle=True, num_workers=0))

In [50]:
point, target = next(c1)
print(point)
print(target)

tensor([[ 2.1683,  0.6383,  2.0928,  0.2337,  3.4871, -1.1373,  1.4543,  1.5345,
         -0.7771, -0.4397,  1.2036, -0.4112, -0.1539],
        [ 0.8054,  0.6383,  0.4118, -0.4553, -0.2851, -1.4303, -0.6836,  0.9793,
         -0.7771, -0.4397,  1.2036, -0.4112, -0.1539],
        [-1.5488, -1.5575,  0.4118, -1.1737, -0.2851,  0.4534, -0.6836, -0.6862,
         -0.7771, -0.4397,  1.2036, -0.4112, -0.1539],
        [ 1.0532, -1.5575, -0.7089,  0.4683, -0.2851,  0.4534, -0.6836,  0.4241,
          1.2793, -0.4397, -0.8260, -0.4112, -0.1539],
        [ 0.8054,  0.6383, -0.7089, -1.1151, -0.2851, -0.0908, -0.6836,  1.5345,
         -0.7771, -0.4397, -0.8260, -0.4112, -0.1539],
        [ 0.1859,  0.6383, -0.1486, -0.6019, -0.2851,  1.2906, -0.6836, -0.6862,
         -0.7771, -0.4397,  1.2036, -0.4112, -0.1539],
        [ 0.1859,  0.6383, -1.8296,  0.0871, -0.2851,  1.4581, -0.6836, -0.6862,
          1.2793, -0.4397, -0.8260, -0.4112, -0.1539],
        [-1.0532,  0.6383,  1.5325, -1.4669,  3.

In [19]:
import numpy as np

In [22]:
# get all unique values from center1.labels, which is a list of tensors
print()

[tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]), tenso

In [26]:
print(center0[3])

(tensor([50.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]), tensor([1.0000e+00, 1.1420e+03]))
